### ISSUE TITLE
Having an issue installing whm_xml

### ISSUE THREAD

**Issue by jumpingcloud** [ivanoats/whm_xml_api_ruby#1]
It's probably my environment:

http://pastebin.com/fSHDpfpd
http://pastebin.com/XWTyCDbt
http://pastebin.com/0KDPX6u8

Please, help, your my only hope!

**Comment by ivanoats** [comment]
is Curl installed and working from the command line?

**Comment by jumpingcloud** [comment]
Hey, Yes it is, I used it to install rvm.

**Comment by jumpingcloud** [comment]
Hey!  I was able to solve it!
I needed this package 
libcurl4-openssl-dev_7.22.0-3ubuntu4_amd64.deb 

Thanks for your reply and this gem!!
